apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-10-17T15:21:16Z"
  labels:
    app: hello-app2
  name: hello-app2
  namespace: default
  resourceVersion: "10639"
  uid: 32f95b72-1f1b-4021-92f0-c6e20e2933f9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.58.203
  clusterIPs:
  - 10.109.58.203
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30319
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}